#!/usr/bin/env bash
# Common Docker entrypoint pattern: validate required env, render config,
# exec the inner command. (We just emit the would-be exec line.)

set -e

: "${APP_USER:=app}"
: "${APP_PORT:=8080}"
: "${LOG_LEVEL:=info}"
: "${DB_URL:=postgres://localhost/test}"

# Render config from template -> /tmp/app.conf.
cat > /tmp/app.conf <<EOF
# Auto-generated by entrypoint.
user = $APP_USER
port = $APP_PORT
log_level = $LOG_LEVEL
db = $DB_URL
EOF

echo "config rendered:"
cat /tmp/app.conf

# Apply migrations if requested (no-op in stub).
if [[ "${RUN_MIGRATIONS:-0}" == "1" ]]; then
  echo "running migrations"
fi

# In a real entrypoint this would be ``exec "$@"``; we emulate by echoing.
if [[ $# -eq 0 ]]; then
  set -- /usr/bin/myapp --listen "0.0.0.0:$APP_PORT"
fi

echo "would exec: $*"
